name: Basic_Image_Library

on: [push]

jobs:
  build-ubuntu:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: cd main_code && mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build main_code/build
      - name: test
        run: cd main_code/build && ctest

  build-windows:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd main_code && mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build main_code/build --config Debug
    - name: test
      run: cd main_code/build && ctest
    
